### ISSUE TITLE
Calling small indels on single-end reads through analysis of soft-clipped reads

### ISSUE THREAD

**Issue by CarlosMackintosh** [dellytools/delly#183]
Hi,

I wonder if delly is able to work on data from single-end reads to call small indels (i.e. by using only soft-clipped read analysis). I am trying it with default parameters or slight modifications (like setting `-s 0`) on bams from reference samples with confirmed deletions (15bp/40bp dels) from single-end reads tech. Delly runs without prompting any error or warning but so far I have been unable to detect any of these deletions (confirmed with other analyses). I am thinking that maybe single-end reads are being discarded because of not having mate information (i.e. split read analysis is not done if there was no detection of abnormal pairs). Even if this is the case, is there a way to make delly skip the read pair analysis stage and directly run the split-read analysis on all reads?

**Comment by tobiasrausch** [comment]
Hi,

Delly >=v0.8.1 should be able to call small InDels from single-end data but InDels need to be larger than >15bp. For 1-25bp, classical short variant callers such as FreeBayes that evaluate intra-read indels (Cigar I and D) perform better compared to tools like Delly that use soft-clips. 

Best, Tobias

**Comment by CarlosMackintosh** [comment]
Hi Tobias,

Thank you for your reply. I used version 0.8.2. 

OK, I get that the 15 bp del is better addressed with SNV/indel variant callers (it is indeed detected by them) but the one 40 bp in size is more problematic. Delly version 0.8.2 is not detecting it so I just wondered if the reason was simply the single-end issue as I read the paper and I got the idea that pair-end filtering was the first step performed by Delly. Thanks for clarifying that this should not be the case. It was probably missed by other reasons. I will try to get other reference samples with similar indels. Anyway if you wish to check it, I could share a bam snippet with you (data from Coriell reference sample NA14094).

**Comment by tobiasrausch** [comment]
If you can share a BAM slice that would be great, thanks. We rarely use SE data so maybe there is still a problem in the code.

**Comment by CarlosMackintosh** [comment]
Hi Tobias,

Ok, thanks. I am attaching it to this post.

The DEL spans chr17:41,246,334-41,246,373 (Deleted ref. seq: GATTCAGACTCCCCATCATGTGAGTCATCAGAACCTAACA)

Just some hints about the data:
- Targeted enrichment by amplicons sequenced by SBS-SNA tech with read average size 120 but with plenty of reads covering more ground (here the del is encompassed by reads 200 - 250 in size). 
- Primers and adapters from library-prep are soft-clipped (I am thinking now that this might be difficulting the detection of the DEL).
- Deep per-base coverage (~500-2000x in the snippet)
- Aligned to hg19 (well, a modified hg19 without unplaced/unlocalized or alt contigs, just the 22+XY chr

Please let me know if you need more info and thanks a lot for taking a look at it.

[NA14094_snippet_hg19.zip](https://github.com/dellytools/delly/files/4261275/NA14094_snippet_hg19.zip)

**Comment by tobiasrausch** [comment]
Thanks. There are indeed tons of soft-clips from primers and adapters in the BAM file. You need to remove these beforehand using cutadapt or similar tools.

**Comment by CarlosMackintosh** [comment]
Hi Tobias,

Thanks. I will try. Not as easy as it seems in this tech though. Thanks anyway for taking a look at it.
