### ISSUE TITLE
split-read assembly fault (Segmentation fault (core dumped))

### ISSUE THREAD

**Issue by zhanghanqing1992** [dellytools/delly#328]
When I used Delly(V1.1.6)to call SV,there is a mistake in step 'split-read assembly'.
this is my COMMAND : 
[2023-Jun-02 17:08:13] delly call -g Gm82a1.fasta -o ZY580A.bcf  ./ZY580A.sorted.dedup.bam
[2023-Jun-02 17:08:17] Paired-end and split-read scanning
[2023-Jun-02 17:09:17] Split-read clustering
[2023-Jun-02 17:09:20] Paired-end clustering
[2023-Jun-02 17:09:25] Split-read assembly
Segmentation fault (core dumped)
So I want to know what‘s wrong with my command and input files,or it's just a bug?

**Comment by tobiasrausch** [comment]
I think that just got fixed by [this commit](https://github.com/dellytools/delly/commit/c65628b8ce83db90c180fa0ce6b52a5debac6926)

**Comment by zhanghanqing1992** [comment]
> I think that just got fixed by [this commit](https://github.com/dellytools/delly/commit/c65628b8ce83db90c180fa0ce6b52a5debac6926)

Thanks Rausch. I found that the file 'src/assemble.h' has already changed, but it still doesn't work correctly, the fault message is as same as that above shows.

**Comment by tobiasrausch** [comment]
Would it be possible to share the BAM and FASTA sequence? This could be another bug.

**Comment by zhanghanqing1992** [comment]
> Would it be possible to share the BAM and FASTA sequence? This could be another bug.

this is the BAM file
![image](https://github.com/dellytools/delly/assets/89249097/998c84c5-288a-4117-aa6a-97cfb53727ad)
and this is FA file
![image](https://github.com/dellytools/delly/assets/89249097/12017c95-3c02-4e43-a73a-5ef824f1f9af)

**Comment by ksc289** [comment]
Good morning,
I'm trying to do the same thing with a reference genome in fasta format and an alignment in bam format and I get the same error. Have you been able to solve the problem?

Thank you very much :)
Karen
